zookeeper:
    image: zookeeper
    ports:
        - 2181:2181

waitzk:
    image: waisbrot/wait
    links:
        - zookeeper

kafka:
    image: ches/kafka
    ports:
        - 7203:7203
        - 9092:9092
    links:
        - zookeeper
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - ZOOKEEPER_IP=127.0.0.1
    extra_hosts:
        - "kafka:127.0.0.1"

suricata:
    image: fooinha/docker-suricata-experimental:sid-kafka
    volumes:
        - /home/pacheco/git/github/Amsterdam/ams/config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
        - /home/pacheco/git/github/Amsterdam/ams/suricata:/var/log/suricata:rw
        - /home/pacheco/git/github/Amsterdam/ams/suricata/run/:/var/run/suricata:rw
        - /home/pacheco/git/github/Amsterdam/ams/config/suricata/ethtool.conf:/etc/supervisor/conf.d/ethtool.conf:ro
        - /home/pacheco/git/github/Amsterdam/ams/scirius/:/etc/suricata/rules:rw
    cap_add:
        - NET_ADMIN
        - NET_RAW
    net: host
    extra_hosts:
        - "kafka:127.0.0.1"
    # TODO set your suricata iface here
    environment:
        - SURICATA_ARGS="--af-packet=eth0"

elasticsearch:
    build: /home/pacheco/git/github/Amsterdam/ams/docker/elasticsearch
    command: -Des.network.bind_host=0.0.0.0 -Des.index.number_of_replicas=0
    volumes:
        - /home/pacheco/git/github/Amsterdam/ams/elasticsearch:/usr/share/elasticsearch/data:rw

logstash:
    image: logstash
    links:
        - elasticsearch
        - kafka
        - zookeeper
    command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/
    volumes:
        - /home/pacheco/git/github/Amsterdam/ams/config/logstash:/etc/logstash:ro
        - /home/pacheco/git/github/Amsterdam/ams/suricata:/var/log/suricata:ro
    hostname: suricata

kibana:
    build: /home/pacheco/git/github/Amsterdam/ams/docker/kibana
    links:
        - elasticsearch

scirius:
    image: stamus/scirius
    volumes:
        - /home/pacheco/git/github/Amsterdam/ams/config/scirius:/etc/scirius:ro
        - /home/pacheco/git/github/Amsterdam/ams/config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
        - /home/pacheco/git/github/Amsterdam/ams/scirius:/etc/suricata/rules:rw
        - /home/pacheco/git/github/Amsterdam/ams/suricata/run:/var/run/suricata:ro
        - /home/pacheco/git/github/Amsterdam/ams/backups:/var/backups:rw
        # TODO uncomment correctly set path to scirius git tree on host below
        # to run a specific scirius version
        #- /path/to/git/stamus/scirius/:/opt/selks/scirius/:ro
    links:
        - elasticsearch
        - kibana
        - evebox
    volumes_from:
        - sciriusdata
        - sciriusstatic

sciriusdata:
    image: busybox
    command: /bin/true
    volumes:
        - /sciriusdata

sciriusstatic:
    image: busybox
    command: /bin/true
    volumes:
        - /sciriusstatic

evebox:
    image: jasonish/evebox:latest
    links:
        - elasticsearch

nginx:
    image: nginx
    ports:
        - 443:443
    volumes: 
        - /home/pacheco/git/github/Amsterdam/ams/config/nginx/amsterdam.conf:/etc/nginx/conf.d/default.conf:ro
        - /home/pacheco/git/github/Amsterdam/ams/config/nginx/ssl/:/etc/nginx/ssl/:ro
    links:
        - scirius
    volumes_from:
        - sciriusstatic
